---
- name: Kiểm tra cấu hình AP Planet qua HTTP API
  hosts: all
  gather_facts: no
  vars:
    api_endpoint: "/api/get-config"  # Thay đổi endpoint này tùy thuộc vào API của AP
    ap_ip: "192.168.10.62"
  tasks:
    - name: Gửi yêu cầu kiểm tra cấu hình từ AP Planet qua Web UI
      uri:
        url: "http://{{ ap_ip }}{{ api_endpoint }}"
        method: GET
        user: "ringnet"  # Thay đổi với tên người dùng của bạn
        password: "Ringnet@123"  # Thay đổi với mật khẩu của bạn
        force_basic_auth: yes
        validate_certs: no
      register: config_response

    - name: Hiển thị cấu hình của AP Planet
      debug:
        var: config_response.json

